In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Clean_Data.csv')

In [3]:
df

Is Captain(1=yes)  Is Wktkeeper(1=Yes)  Nationality(1=Overseas)  \
0                  0.0                  0.0                        1   
1                  0.0                  0.0                        1   
2                  0.0                  0.0                        1   
3                  0.0                  0.0                        1   
4                  0.0                  0.0                        1   
..                 ...                  ...                      ...   
124                0.0                  0.0                        0   
125                0.0                  0.0                        0   
126                0.0                  1.0                        0   
127                0.0                  0.0                        0   
128                1.0                  0.0                        0   

                  Name          Team              IPL 4 Franchise  \
0       Aiden Blizzard     Australia               Mumbai Indians   
1     Jonathan Vandiar  South Africa  Royal Challengers Bangalore   
2    Nathan Rimmington     Australia              Kings XI Punjab   
3        Rilee Rossouw  South Africa  Royal Challengers Bangalore   
4      Robert Frylinck  South Africa             Delhi Daredevils   
..                 ...           ...                          ...   
124       Irfan Pathan         India             Delhi Daredevils   
125       Rohit Sharma         India               Mumbai Indians   
126      Robin Uthappa         India                Pune Warriors   
127       Yusuf Pathan         India        Kolkata Knight Riders   
128     Gautam Gambhir         India        Kolkata Knight Riders   

     Player cost USD  matches  innings played    no  ...  half_centuries_ipl  \
0            20000.0     40.0            40.0   3.0  ...                 0.0   
1            20000.0     18.0            18.0   1.0  ...                 0.0   
2            20000.0     23.0             8.0   5.0  ...                 0.0   
3            20000.0     20.0            20.0   0.0  ...                 0.0   
4            20000.0     25.0            22.0   8.0  ...                 0.0   
..               ...      ...             ...   ...  ...                 ...   
124        1900000.0     83.0            67.0  23.0  ...                 1.0   
125        2000000.0     97.0            91.0  18.0  ...                 0.0   
126        2100000.0     93.0            87.0  14.0  ...                 3.0   
127        2100000.0     90.0            82.0  10.0  ...                 2.0   
128        2400000.0     87.0            85.0   9.0  ...                 2.0   

     fours_ipl  sixes_ipl  matches_bowl_ipl  balls_bowled_ipl  \
0          0.0        0.0               0.0               0.0   
1          0.0        0.0               0.0               0.0   
2          0.0        0.0               0.0               0.0   
3          0.0        0.0               0.0               0.0   
4          0.0        0.0               0.0               0.0   
..         ...        ...               ...               ...   
124       21.0       10.0              14.0             290.0   
125        3.0        1.0               6.0             126.0   
126       21.0       27.0               0.0               0.0   
127       22.0       24.0              11.0             214.0   
128       32.0        2.0               0.0               0.0   

     total_runs_given_ipl  wickets_taken_ipl  bowling_avg_ipl  economy_ipl  \
0                     0.0                0.0         0.000000     0.000000   
1                     0.0                0.0         0.000000     0.000000   
2                     0.0                0.0         0.000000     0.000000   
3                     0.0                0.0         0.000000     0.000000   
4                     0.0                0.0         0.000000     0.000000   
..                    ...                ...              ...          ...   
124                 414

In [4]:
df=df.drop('Name',axis=1)

In [5]:
data = pd.get_dummies(df, columns=['Team', 'IPL 4 Franchise'])
data.shape

(129, 68)

In [6]:
X = data.drop('Retained', axis=1)
y = data['Retained']

In [28]:
y_0=df[df['Retained']==0]
y_1=df[df['Retained']==1]
y_0.shape
#y_1.shape

(117, 51)

In [7]:
cols = X.columns

In [8]:
from sklearn.preprocessing import StandardScaler 
X = StandardScaler().fit_transform(X)

In [9]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# SIMPLE LOGISTIC REGRESSION

In [10]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)

In [11]:
y_pred=clf.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[34,  2],
       [ 2,  1]], dtype=int64)

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred)) 

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        36
           1       0.33      0.33      0.33         3

    accuracy                           0.90        39
   macro avg       0.64      0.64      0.64        39
weighted avg       0.90      0.90      0.90        39



What is macro avg and weighted avg?

# LR using K-Fold

In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean
model = LogisticRegression(solver='lbfgs') #what is lbfgs is?
# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.3f' % mean(scores))

Mean ROC AUC: 0.828


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred)) 


              precision    recall  f1-score   support

           0       0.94      0.94      0.94        36
           1       0.33      0.33      0.33         3

    accuracy                           0.90        39
   macro avg       0.64      0.64      0.64        39
weighted avg       0.90      0.90      0.90        39



In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean
model = LogisticRegression(solver='lbfgs') #what is lbfgs is?
# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.3f' % mean(scores))

Mean ROC AUC: 0.828


# LR Using Class Weights

In [19]:
#defining class weights(0=majority,1=minority)
weights = {0:1.0, 1:10.0}
model = LogisticRegression(solver='lbfgs', class_weight=weights)

In [20]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.3f' % mean(scores))

Mean ROC AUC: 0.830


In [21]:
weights_1 = {0:1.0, 1:10.0}
model_1 = LogisticRegression(solver='lbfgs', class_weight=weights)

In [22]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.3f' % mean(scores))

Mean ROC AUC: 0.830


In [23]:
balance = [{0:1,1:100}, {0:1,1:10}, {0:1,1:1}, {0:1,1:50}, {0:0.5,1:5}]
param_grid = dict(class_weight=balance)

In [24]:
from sklearn.model_selection import GridSearchCV
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# define grid search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='roc_auc')

In [25]:
grid_result = grid.fit(X, y)
# report the best configuration
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
# report all configurations
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))


Best: 0.830556 using {'class_weight': {0: 0.5, 1: 5}}
0.814394 (0.162114) with: {'class_weight': {0: 1, 1: 100}}
0.830303 (0.158073) with: {'class_weight': {0: 1, 1: 10}}
0.827778 (0.158584) with: {'class_weight': {0: 1, 1: 1}}
0.815909 (0.161076) with: {'class_weight': {0: 1, 1: 50}}
0.830556 (0.157926) with: {'class_weight': {0: 0.5, 1: 5}}


In [27]:
print("accuracy :",grid_result.best_score_)

accuracy : 0.8305555555555555


In [2]:
import numpy as np
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [3]:
print(c)

[[-0.12759282 -0.08914201  0.08925179]
 [-0.1697527   0.34341142  0.88223859]
 [ 0.4426813   0.06530926  1.24389017]]
